# Generated by Django 5.0.1 on 2024-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfdIv7mYroRcEro01QihNy4FertDfXFWtetQ&usqp=CAU', max_length=500),
        ),
    ]
